app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::resource('products', 'ProductController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'body',
    ];

}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

use App\Http\Requests;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('id', 'DESC')->paginate();
        $data = [
            "products" => $products
        ];
        return view('products.index',$data);
    }

   /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = new Product;
        $product->name = $request->name;
        $product->description = $request->description;
        $product->body = $request->body;
        $product->save();
        return redirect()->route('products.index')->with('info','Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        return view('home');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $data = [
            "product" => $product
        ];
        return view('products.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        $product->name = $request->name;
        $product->description = $request->description;
        $product->body = $request->body;
        $product->save();
        return redirect()->route('products.index')->with('info','Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        $product->delete();
        return back()->with('info','Deleted');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <!-- Custom -->
    <link rel="stylesheet" href="{!! asset('css/app.css') !!}">

    @yield('styles')

</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="col-xs-12">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ route('products.index') }}">
                    Store
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Moda</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                               <i class="fa fa-user"></i> {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')


    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
    <!-- Sweetalert -->
    <script src="{!! asset('sweetalert/sweetalert.js') !!}"></script>
    
    @yield('script')
</body>
</html>

resources/views/products/add.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="col-xs-12">
            <a href="{{ route('products.index') }}" class="btn color-blue pull-right"><i class="fa fa-cubes"></i>Products</a>
        </div>
        <div class="row">
            <form action="{{ route('products.store') }}" method="POST">
                {{ csrf_field() }}
                @include('products.components.form')
                <input type='submit' class='btn btn-primary' value='ENVIAR' />
            </form>
        </div>
    </div>
@endsection

resources/views/products/components/form.blade.php
 <div class="col-xs-12">
     <div class="form-group">
         <label for="name">Product name</label>
         <input type="text" id="name" name="name" class="form-control" value="@if(!empty($product->name)) {{ $product->name }} @endif" />
     </div>

     <div class="form-group">
         <label for="description">Description</label>
         <input type="text" id="description" name="description" class="form-control" value="@if(!empty($product->description)) {{ $product->description }} @endif" />
     </div>

     <div class="form-group">
         <label for="body">Body</label>
         <input type="text" id="body" name="body" class="form-control" value="@if(!empty($product->body)) {{ $product->body }}  @endif" />
     </div>
 </div>

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="col-xs-12">
            <a href="{{ route('products.index') }}" class="btn color-blue pull-right"><i class="fa fa-cubes"></i>Products</a>
        </div>
        <div class="row">
            <form action="{{ route('products.update', $product->id) }}" method="POST">
                {{ csrf_field() }}
                @include('products.components.form')
                <input  type="hidden" name="_method" value="PUT" />
                <input type='submit' class='btn btn-primary' value='ENVIAR' />
            </form>
        </div>
    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
   <div class="container">

      <div class="col-xs-12">
          <a href="{{ route('products.create') }}" class="btn color-blue pull-right"><i class="fa fa-cube"></i> <i class="fa fa-plus"></i></a>

          @if(Session::has('info'))
              <input type="hidden" class="info" value="{{ Session::get('info') }}">
          @endif
      </div>
      <div class="row">
          <table class="table table-striped">
              <thead>
              <th>Name</th>
              <th>Description</th>
              <th>Body</th>
              <th>Edit</th>
              <th>Delete</th>
              </thead>
              <tbody>
              @foreach($products as $product)
                  <tr>
                      <td>{{ $product->name }}</td>
                      <td>{{ $product->description }}</td>
                      <td>{{ $product->body }}</td>
                      <td>
                          <form action="{{ route('products.edit', $product->id) }}" method="GET">
                              {{ csrf_field() }}
                              <input  type="hidden" name="_method" value="GET" />
                              <button class="btn btn-default color-blue"><i class="fa fa-pencil"></i></button>
                          </form></td>
                      <td>
                          <form class="form-delete" action="{{ route('products.destroy', $product->id) }}" method="POST">
                              {{ csrf_field() }}
                              <input  type="hidden" name="_method" value="DELETE" />
                              <a class="btn btn-default btn-delete color-red"><i class="fa fa-trash"></i></a>
                          </form>
                      </td>
                  </tr>
              @endforeach
              </tbody>
          </table>
      </div>

   </div>

@endsection

@section('script')
    <!-- Javascript local page -->
    <script src="{!! asset('js/products/delete.js') !!}"></script>
    <script src="{!! asset('js/products/index.js') !!}"></script>
@endsection